// Generated by tools/ik_walk_simulator/export_firmware_presets.py; do not edit.
#pragma once
namespace IkWalk {
struct GaitPreset { const char *key; float stride,lift,turn,period,duty,offset[4],startPhase,bodyHeight,opening; };
static const float defaultComX=0.000000f, defaultComY=0.000000f, defaultComMargin=2.000000f;
static const GaitPreset gaitPresets[3] = {
  {"WALK",18.000000f,12.000000f,4.000000f,4.000000f,0.850000f,{0.000000f,0.500000f,0.750000f,0.250000f},0.000000f,0.000000f,0.000000f},
  {"WAVE",18.000000f,12.000000f,4.000000f,2.400000f,0.850000f,{0.000000f,0.500000f,0.750000f,0.250000f},0.000000f,0.000000f,0.000000f},
  {"TROT",18.000000f,12.000000f,4.000000f,2.400000f,0.620000f,{0.000000f,0.500000f,0.500000f,0.000000f},0.000000f,0.000000f,0.000000f},
};
}
