"""Generate the AVR-friendly preset table from gait_defaults.json."""
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
SOURCE = HERE / "gait_defaults.json"
OUTPUT = ROOT / "mini_qpod_ik_walk_mvp" / "gait_presets.h"


def render(data):
    presets = data["presets"]
    lines = [
        "// Generated by tools/ik_walk_simulator/export_firmware_presets.py; do not edit.",
        "#pragma once", "namespace IkWalk {",
        "struct GaitPreset { const char *key; float stride,lift,turn,period,duty,offset[4],startPhase,bodyHeight,opening; };",
        f"static const float defaultComX={data['com_estimate']['x_mm']:.6f}f, defaultComY={data['com_estimate']['y_mm']:.6f}f, defaultComMargin={data['com_estimate']['balance_margin_mm']:.6f}f;",
        f"static const GaitPreset gaitPresets[{len(presets)}] = {{",
    ]
    for key, p in presets.items():
        offsets = ",".join(f"{v:.6f}f" for v in p["phase_offsets"])
        lines.append(
            f'  {{"{key}",{p["stride"]:.6f}f,{p["lift"]:.6f}f,'
            f'{p["turn_degrees"]:.6f}f,{p["period"]:.6f}f,{p["duty"]:.6f}f,'
            f'{{{offsets}}},{p["start_phase"]:.6f}f,{p.get("body_height_mm",0):.6f}f,{p.get("leg_opening_mm",0):.6f}f}},'
        )
    lines.extend(["};", "}", ""])
    return "\n".join(lines)


def main():
    OUTPUT.write_text(render(json.loads(SOURCE.read_text(encoding="utf-8"))), encoding="utf-8")


if __name__ == "__main__":
    main()
